### ISSUE TITLE
Conflicts with UITableView delete gesture

### ISSUE THREAD

**Issue by ReDetection** [Enricoza/EZCustomNavigation#5] opened 2021-01-12 04:36 UTC
Hi. Pan-to-pop gesture seems to break swipe-to-delete gesture in UITableView. What is most funny it is still possible to swipe-to-delete but you have to put your finger very fast!

[demo branch with table view is in my fork](https://github.com/ReDetection/EZCustomNavigation/tree/tableview-bug-demo)

**Comment by Enricoza** [comment] 2021-01-12 18:35
Thank you for your report and for the demo branch @ReDetection, it was really helpful.

I'm working on this right now and will be releasing the fix asap.

**Comment by Enricoza** [comment] 2021-01-12 20:49
Hi again @ReDetection, 
the `v1.1.1` release should solve your problem.
Thank you again for your time spent in opening the issue and creating the branch for me.

I'm going to close this issue but feel free to reopen or open a new one if something is still wrong.

PS: while looking into this I found another issue with the `leadingSwipeActions` of the table view for which I created a separate issue (#6) since it's going to need more attention.

**Closed as completed by Enricoza** 2021-01-12 20:49 UTC
Labels: bug

**Comment by ReDetection** [comment] 2021-01-13 01:55
Thanks you so much for the quick actions :)

Yeah, I tried to go with a fix too, but I stuck at the exact same issue, just with different gesture: if you leave cell in the middle state, when it has Delete button revealed, but not confirmed, you can't close it with a swipe to the right – pop to dismiss interferes. Anyway, I agree it is basically the same as #6 so it makes sense to continue there

**Comment by Enricoza** [comment] 2021-01-13 08:27
Hi again @ReDetection, 
From my tests it seemed to work properly (even if I'm not entirely sure why)

Did you have this problem every time or just in some cases? Did you try my sample from the master branch?
(Maybe in your app this is having some other kind of conflicts)
Or maybe It happens only on some iOS versions that I haven't tested...

**Comment by Enricoza** [comment] 2021-01-13 18:24
I can confirm that, oddly enough, this works perfectly on iOS 12 while on iOS 14 it has the slight disadvantage that you can't swipe the delete button out (but you can still tap anywhere to dismiss it).
I guess it's still better than before so we can move the discussion on the other thread.
